#!/bin/bash

function makepdf {
	pandoc -f gfm -t pdf $1 -o /tmp/mark.pdf -V geometry:margin=0.8in -V urlcolor='[HTML]{0000ff}' -V 'fontfamily:dejavu'
}

function makepdfimage {
	pdftoppm -singlefile -f 1 -r 72 -jpeg -jpegopt quality=90 /tmp/mark.pdf /tmp/mark
}

function drawimage {
	source "`ueberzug library`"
	if [ "$5" != "" ]
	then
	# process substitution example:
	ImageLayer 0< <(
		ImageLayer::add [identifier]="example0" [x]="$3" [y]="$4" \
			 [width]="$5" [path]="$1"
		
		sleep "$2"
		
		#TODO: doesn't work. Images don't stay. They always get removed
#		if [ "$5" != "no-remove" ]
#		then
#			ImageLayer::remove [identifier]="example0"
#		fi
	)
	else
	ImageLayer 0< <(
		ImageLayer::add [identifier]="example0" [x]="$3" [y]="$4"\
		[path]="$1"
		
		sleep "$2"
	)
	fi
	
}

function makeclear {
	rm -f /tmp/mark*
}

if [ "$1" = "" ] || [ $# -gt 5 ] || [ ! -f "$1" ]
then
	echo "Usage: img file.md | imagefile [sleep-seconds] [x y] [width]"
else
	case $(file -b --mime-type "$1") in
		text/*)
			makepdf "$1"
			makepdfimage
			drawimage "/tmp/mark.jpg" "5" "39" "0" "40"
			;;
		image/*)
			if [ "$#" -lt 5 ]
			then
				drawimage "$1" "3" "39" "0" ""
			else
				drawimage "$@"
			fi
			;;
		*)
			echo "file not supported"
			;;
	esac
fi

makeclear
